### ISSUE TITLE
Tag 1.0 release

### ISSUE THREAD

**Issue by misterbisson** [tgross/triton-touchbase#11]
The upcoming release of TCNS will obviate the need for CloudFlare in this blueprint. Let's tag the current version as 1.0 so that we can preserve it while updating the blueprint for TCNS.

**Comment by tgross** [comment]
Done: https://github.com/tgross/triton-touchbase/releases/tag/1.0.
For updating the link from the old blog post we might consider linking to https://github.com/tgross/triton-touchbase/tree/1.0 rather than the releases tab.

**Comment by tgross** [comment]
Per your offline comment the changes will be under separate PR. Closing this issue as done.
