### ISSUE TITLE
Not using my environment variables to set couchbase uname/password

### ISSUE THREAD

**Issue by mbbender** [tgross/triton-touchbase#2]
I'm not sure why it isn't using them. I added export to every line in the environment file in an attempt to ensure they were exported and available but still setting as Adminstrator / password and then when it tries to create the buckets it is actually using the variables set in the environment file.

**Comment by mbbender** [comment]
Ah, it appears to be hardcoded in the docker-compose files. Not sure how to make those read from the environment or I'd send a pull request.

**Comment by misterbisson** [comment]
I believe that stanza of the [`docker-compose.yml`](https://github.com/tgross/triton-touchbase/blob/master/docker-compose.yml) should read as follows:

``` yaml
    environment:
        - CONSUL_HOST=http://consul:8500
        - COUCHBASE_SERVICE_NAME=couchbase
        - COUCHBASE_USER
        - COUCHBASE_PASS
```

That syntax should cause Compose to inherit the values for `COUCHBASE_USER` and `COUCHBASE_PASS` from the environment.

**Comment by mbbender** [comment]
The sample env file uses CB_USER and CB_PASSWORD so I guess that would be a simple update to make if necessary.

**Comment by tgross** [comment]
Fixed in https://github.com/tgross/triton-touchbase/pull/5
