### ISSUE TITLE
Typo in docker-compose-local.yml

### ISSUE THREAD

**Issue by seankibler** [tgross/triton-touchbase#24]
The `mem_limit` for the prometheus container is set to **128G** when it probably is meant to be **128M**.

Link direct to source:
https://github.com/autopilotpattern/touchbase/blob/master/docker-compose-local.yml#L85

I have created a pull request with a fix #25

**Comment by tgross** [comment]
Fixed in https://github.com/autopilotpattern/touchbase/pull/25. Thanks @seankibler !
