### ISSUE TITLE
"Proxy" the Couchbase API requests through docker exec`

### ISSUE THREAD

**Issue by misterbisson** [tgross/triton-touchbase#3]
[`removeBucket`](https://github.com/tgross/triton-touchbase/blob/master/start.sh#L97-L101) and [`createIndex`](https://github.com/tgross/triton-touchbase/blob/master/start.sh#L118-L123) assume they can reach the API on the public internet. Those commands should probably be passed through `docker exec...`.

**Comment by tgross** [comment]
Resolved in https://github.com/tgross/triton-touchbase/issues/6
